/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["root_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_activity_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_apps_retrieve"];
        put?: never;
        post: operations["admin_apps_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["admin_apps_destroy"];
        options?: never;
        head?: never;
        patch: operations["admin_apps_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/apps/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["admin_apps_import_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/catalog/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_catalog_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["admin_categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["admin_categories_destroy"];
        options?: never;
        head?: never;
        patch: operations["admin_categories_partial_update"];
        trace?: never;
    };
    "/api/v1/admin/cleanup-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["admin_cleanup_tokens_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/recompute-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["admin_recompute_counts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["admin_settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["admin_settings_partial_update"];
        trace?: never;
    };
    "/api/v1/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apps_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apps_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/by-slug/{platform}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apps_by_slug_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email-change/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_email_change_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_resend_verification_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_by_slug_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["collections_list"];
        put?: never;
        post: operations["collections_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["collections_retrieve"];
        put?: never;
        post?: never;
        delete: operations["collections_destroy"];
        options?: never;
        head?: never;
        patch: operations["collections_partial_update"];
        trace?: never;
    };
    "/api/v1/collections/{id}/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["collections_apps_partial_update"];
        trace?: never;
    };
    "/api/v1/collections/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["collections_public_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["favorites_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites/{app_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["favorites_create"];
        delete: operations["favorites_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["favorites_ids_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scripts/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["scripts_generate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scripts/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["scripts_history_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_retrieve"];
        put?: never;
        post?: never;
        delete: operations["user_destroy"];
        options?: never;
        head?: never;
        patch: operations["user_partial_update"];
        trace?: never;
    };
    "/api/v1/user/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_change_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_sessions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["user_sessions_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_ready_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityLog: {
            readonly id: number;
            /** Format: uuid */
            readonly user_id: string | null;
            readonly action: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly target_type: string;
            readonly target_id: string;
            readonly client_ip: string;
            readonly request_id: string;
            readonly user_agent: string;
            readonly detail: unknown;
            /** Format: date-time */
            readonly created_at: string;
        };
        AppDetail: {
            readonly id: number;
            readonly category_id: number;
            readonly category_name: string;
            readonly category_slug: string;
            readonly platform: components["schemas"]["PlatformEnum"];
            readonly name: string;
            readonly slug: string;
            readonly summary: string;
            /** Format: uri */
            readonly homepage_url: string;
            /** Active */
            readonly is_active: boolean;
            readonly description: string;
            readonly license: string;
            readonly package_refs: components["schemas"]["PackageReference"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        AppImportRequest: {
            apps: components["schemas"]["AppWriteRequest"][];
        };
        AppList: {
            readonly id: number;
            readonly category_id: number;
            readonly category_name: string;
            readonly category_slug: string;
            readonly platform: components["schemas"]["PlatformEnum"];
            readonly name: string;
            readonly slug: string;
            readonly summary: string;
            /** Format: uri */
            readonly homepage_url: string;
            /** Active */
            readonly is_active: boolean;
        };
        AppWriteRequest: {
            category_id: number;
            platform: components["schemas"]["PlatformEnum"];
            name: string;
            summary?: string;
            description?: string;
            homepage_url?: string;
            license?: string;
            /** Active */
            is_active?: boolean;
            package_refs?: components["schemas"]["PackageReferenceRequest"][];
        };
        CatalogExport: {
            readonly categories: components["schemas"]["Category"][];
            readonly apps: components["schemas"]["AppDetail"][];
        };
        Category: {
            readonly id: number;
            readonly name: string;
            readonly slug: string;
            readonly description: string;
            /** Format: uri */
            readonly icon_url: string;
            readonly windows_app_count: number;
            readonly linux_app_count: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        CategoryWriteRequest: {
            name: string;
            description?: string;
            icon_url?: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        Collection: {
            readonly id: number;
            /**
             * Owner
             * Format: uuid
             */
            readonly user_id: string;
            readonly name: string;
            readonly slug: string;
            readonly description: string;
            /** Public */
            readonly is_public: boolean;
            readonly item_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        CollectionDetail: {
            readonly id: number;
            /**
             * Owner
             * Format: uuid
             */
            readonly user_id: string;
            readonly name: string;
            readonly slug: string;
            readonly description: string;
            /** Public */
            readonly is_public: boolean;
            readonly item_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly items: components["schemas"]["CollectionItem"][];
        };
        CollectionItem: {
            readonly app: components["schemas"]["AppList"];
            readonly position: number;
        };
        CollectionWriteRequest: {
            name: string;
            description?: string;
            /** Public */
            is_public?: boolean;
            app_ids?: number[];
        };
        DataExport: {
            readonly user: components["schemas"]["User"];
            readonly collections: components["schemas"]["ExportCollection"][];
            readonly favorites: number[];
            readonly script_runs: components["schemas"]["ExportScriptRun"][];
        };
        /**
         * @description * `console` - Console
         *     * `smtp` - SMTP
         * @enum {string}
         */
        EmailBackendEnum: "console" | "smtp";
        EmailChangeRequestRequest: {
            /** Format: email */
            new_email: string;
            current_password: string;
        };
        EmailRequest: {
            /** Format: email */
            email: string;
        };
        ExportCollection: {
            readonly id: number;
            readonly name: string;
            readonly slug: string;
            readonly is_public: boolean;
            readonly app_ids: number[];
            /** Format: date-time */
            readonly created_at: string;
        };
        ExportScriptRun: {
            readonly id: number;
            readonly platform: string;
            readonly app_ids: number[];
            /** Format: date-time */
            readonly created_at: string;
        };
        Health: {
            readonly status: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /**
         * @description * `winget` - winget
         *     * `msstore` - Microsoft Store
         *     * `apt` - APT
         *     * `dnf` - DNF
         *     * `pacman` - pacman
         *     * `flatpak` - Flatpak
         *     * `snap` - Snap
         *     * `direct` - Direct download
         * @enum {string}
         */
        ManagerEnum: "winget" | "msstore" | "apt" | "dnf" | "pacman" | "flatpak" | "snap" | "direct";
        Message: {
            readonly message: string;
        };
        PackageReference: {
            readonly id: number;
            manager: components["schemas"]["ManagerEnum"];
            identifier: string;
            install_args?: string;
            priority?: number;
            extra?: unknown;
        };
        PackageReferenceRequest: {
            manager: components["schemas"]["ManagerEnum"];
            identifier: string;
            install_args?: string;
            priority?: number;
            extra?: unknown;
        };
        PageMeta: {
            readonly page: number;
            readonly size: number;
            readonly total: number;
            readonly pages: number;
        };
        PaginatedActivityLogList: {
            readonly items: components["schemas"]["ActivityLog"][];
            readonly meta: components["schemas"]["PageMeta"];
        };
        PaginatedAdminAppList: {
            readonly items: components["schemas"]["AppList"][];
            readonly meta: components["schemas"]["PageMeta"];
        };
        PaginatedAppList: {
            readonly items: components["schemas"]["AppList"][];
            readonly meta: components["schemas"]["PageMeta"];
        };
        PaginatedCategoryList: {
            readonly items: components["schemas"]["Category"][];
            readonly meta: components["schemas"]["PageMeta"];
        };
        PaginatedCollectionList: {
            readonly items: components["schemas"]["Collection"][];
            readonly meta: components["schemas"]["PageMeta"];
        };
        PaginatedFavoriteList: {
            readonly items: components["schemas"]["AppList"][];
            readonly meta: components["schemas"]["PageMeta"];
        };
        PaginatedPublicCollectionList: {
            readonly items: components["schemas"]["Collection"][];
            readonly meta: components["schemas"]["PageMeta"];
        };
        PaginatedScriptRunList: {
            readonly items: components["schemas"]["ScriptRun"][];
            readonly meta: components["schemas"]["PageMeta"];
        };
        PasswordResetConfirmRequest: {
            uid: string;
            token: string;
            new_password: string;
        };
        PatchedAppWriteRequest: {
            category_id?: number;
            platform?: components["schemas"]["PlatformEnum"];
            name?: string;
            summary?: string;
            description?: string;
            homepage_url?: string;
            license?: string;
            /** Active */
            is_active?: boolean;
            package_refs?: components["schemas"]["PackageReferenceRequest"][];
        };
        PatchedCategoryWriteRequest: {
            name?: string;
            description?: string;
            icon_url?: string;
        };
        PatchedCollectionSetAppsRequest: {
            app_ids?: number[];
        };
        PatchedCollectionWriteRequest: {
            name?: string;
            description?: string;
            /** Public */
            is_public?: boolean;
            app_ids?: number[];
        };
        PatchedSiteConfigurationUpdateRequest: {
            registration_enabled?: boolean | null;
            email_enabled?: boolean | null;
            rate_limit_enabled?: boolean | null;
            rate_limit_default?: string;
            rate_limit_auth?: string;
            email_backend?: components["schemas"]["EmailBackendEnum"];
            email_from?: (string) | null;
            smtp_host?: string | null;
            smtp_port?: number | null;
            smtp_user?: string | null;
            smtp_password?: string | null;
            smtp_use_tls?: boolean | null;
            project_name?: string | null;
            frontend_base_url?: (string) | null;
        };
        PatchedUserUpdateRequest: {
            full_name?: string;
        };
        /**
         * @description * `windows` - Windows
         *     * `linux` - Linux
         * @enum {string}
         */
        PlatformEnum: "windows" | "linux";
        Readiness: {
            readonly status: {
                [key: string]: string;
            };
        };
        RecomputeCounts: {
            readonly message: string;
            readonly categories: number;
        };
        RefreshRequest: {
            refresh: string;
        };
        RegisterRequest: {
            /**
             * Email address
             * Format: email
             */
            email: string;
            password: string;
            full_name?: string;
        };
        ScriptGenerateRequest: {
            platform: components["schemas"]["PlatformEnum"];
            app_ids?: number[];
            collection_id?: number | null;
        };
        ScriptRun: {
            readonly id: number;
            readonly platform: components["schemas"]["PlatformEnum"];
            readonly app_ids: number[];
            readonly app_count: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        ServiceInfo: {
            readonly service: string;
            readonly version: string;
            readonly status: string;
        };
        Session: {
            readonly id: number;
            /** Format: date-time */
            readonly created_at: string | null;
            /** Format: date-time */
            readonly expires_at: string;
            /** @default  */
            readonly user_agent: string;
            /** @default  */
            readonly client_ip: string;
            /** Format: date-time */
            readonly last_used_at: string;
        };
        SiteConfigurationRead: {
            registration_enabled: boolean;
            email_enabled: boolean;
            rate_limit_enabled: boolean;
            rate_limit_default: string;
            rate_limit_auth: string;
            email_backend: string;
            email_from: string;
            smtp_host: string;
            smtp_port: number;
            smtp_user: string;
            smtp_password_set: boolean;
            smtp_use_tls: boolean;
            project_name: string;
            frontend_base_url: string;
        };
        /**
         * @description * `ok` - OK
         *     * `failure` - Failure
         * @enum {string}
         */
        StatusEnum: "ok" | "failure";
        TokenOnlyRequest: {
            token: string;
        };
        TokenPair: {
            readonly access: string;
            readonly refresh: string;
        };
        UidTokenRequest: {
            uid: string;
            token: string;
        };
        User: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            readonly full_name: string;
            readonly role: string;
            /** Active */
            readonly is_active: boolean;
            /** Email verified */
            readonly is_verified: boolean;
            /**
             * Date joined
             * Format: date-time
             */
            readonly created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInfo"];
                };
            };
        };
    };
    admin_activity_retrieve: {
        parameters: {
            query?: {
                action?: string;
                page?: number;
                since?: string;
                size?: number;
                status?: string;
                target_type?: string;
                until?: string;
                user_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedActivityLogList"];
                };
            };
        };
    };
    admin_apps_retrieve: {
        parameters: {
            query?: {
                category_id?: number;
                page?: number;
                platform?: "linux" | "windows";
                q?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAdminAppList"];
                };
            };
        };
    };
    admin_apps_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AppWriteRequest"];
                "multipart/form-data": components["schemas"]["AppWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetail"];
                };
            };
        };
    };
    admin_apps_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_apps_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAppWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAppWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedAppWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetail"];
                };
            };
        };
    };
    admin_apps_import_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppImportRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AppImportRequest"];
                "multipart/form-data": components["schemas"]["AppImportRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetail"][];
                };
            };
        };
    };
    admin_catalog_export_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogExport"];
                };
            };
        };
    };
    admin_categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CategoryWriteRequest"];
                "multipart/form-data": components["schemas"]["CategoryWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    admin_categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategoryWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategoryWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedCategoryWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    admin_cleanup_tokens_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    admin_recompute_counts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeCounts"];
                };
            };
        };
    };
    admin_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteConfigurationRead"];
                };
            };
        };
    };
    admin_settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSiteConfigurationUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSiteConfigurationUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedSiteConfigurationUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteConfigurationRead"];
                };
            };
        };
    };
    apps_list: {
        parameters: {
            query?: {
                category_id?: number;
                page?: number;
                platform?: "linux" | "windows";
                q?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAppList"];
                };
            };
        };
    };
    apps_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetail"];
                };
            };
        };
    };
    apps_by_slug_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppDetail"];
                };
            };
        };
    };
    auth_email_change_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenOnlyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenOnlyRequest"];
                "multipart/form-data": components["schemas"]["TokenOnlyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RefreshRequest"];
                "multipart/form-data": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailRequest"];
                "multipart/form-data": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RefreshRequest"];
                "multipart/form-data": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_resend_verification_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailRequest"];
                "multipart/form-data": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    auth_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UidTokenRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UidTokenRequest"];
                "multipart/form-data": components["schemas"]["UidTokenRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    categories_list: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCategoryList"];
                };
            };
        };
    };
    categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_by_slug_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    collections_list: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCollectionList"];
                };
            };
        };
    };
    collections_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CollectionWriteRequest"];
                "multipart/form-data": components["schemas"]["CollectionWriteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
        };
    };
    collections_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
        };
    };
    collections_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    collections_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCollectionWriteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCollectionWriteRequest"];
                "multipart/form-data": components["schemas"]["PatchedCollectionWriteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
        };
    };
    collections_apps_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCollectionSetAppsRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCollectionSetAppsRequest"];
                "multipart/form-data": components["schemas"]["PatchedCollectionSetAppsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionDetail"];
                };
            };
        };
    };
    collections_public_retrieve: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPublicCollectionList"];
                };
            };
        };
    };
    favorites_retrieve: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedFavoriteList"];
                };
            };
        };
    };
    favorites_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    favorites_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    favorites_ids_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
        };
    };
    scripts_generate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScriptGenerateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ScriptGenerateRequest"];
                "multipart/form-data": components["schemas"]["ScriptGenerateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    scripts_history_retrieve: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedScriptRunList"];
                };
            };
        };
    };
    user_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    user_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    user_change_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePasswordRequest"];
                "multipart/form-data": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    user_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailChangeRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmailChangeRequestRequest"];
                "multipart/form-data": components["schemas"]["EmailChangeRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    user_export_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataExport"];
                };
            };
        };
    };
    user_sessions_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
        };
    };
    user_sessions_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    health_ready_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
}
